services:
  mysql:
    image: mysql:latest
    container_name: weather-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather
      MYSQL_USER: weather_user
      MYSQL_PASSWORD: weather_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/initWeatherDatabase.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
